"""Generate README.md and per-topic paper lists (docs/papers/*.md)."""

from __future__ import annotations

import logging
import re
from datetime import datetime
from pathlib import Path
from typing import Any

from . import config, translator
from .categorizer import get_statistics, group_by_category
from .summarizer import short_authors

logger = logging.getLogger(__name__)

GENERATED_MARKER = "<!-- Generated by 3DGenomeHub (src/genome_literature/readme_generator.py). Do not edit by hand. -->"
ML_PAGE_SLUG = "ai-ml-3d-genome"
LATEST_ML_ROWS = 20
LATEST_OTHER_ROWS = 10
TOP_CITED_ROWS = 20


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def github_anchor(heading: str) -> str:
    """Anchor GitHub generates for a heading."""
    s = re.sub(r"[^\w\- ]", "", heading.strip().lower())
    return s.replace(" ", "-")


def md_escape(text: str) -> str:
    return re.sub(r"([\\`*_\[\]<>|])", r"\\\1", text or "").replace("\n", " ")


def badge(label: str, message: Any, color: str) -> str:
    def enc(s: Any) -> str:
        return str(s).replace("-", "--").replace("_", "__").replace(" ", "%20").replace("/", "%2F")
    return f"![{label}](https://img.shields.io/badge/{enc(label)}-{enc(message)}-{color})"


def paper_links(p: dict[str, Any]) -> str:
    links = []
    if p.get("doi"):
        links.append(f"[DOI](https://doi.org/{p['doi']})")
    if p.get("pmid"):
        links.append(f"[PubMed](https://pubmed.ncbi.nlm.nih.gov/{p['pmid']}/)")
    if p.get("arxiv_id"):
        links.append(f"[arXiv](https://arxiv.org/abs/{p['arxiv_id']})")
    if p.get("pdf_url"):
        links.append(f"[PDF]({p['pdf_url']})")
    if not links and p.get("url"):
        links.append(f"[Link]({p['url']})")
    return " · ".join(links)


def tags(p: dict[str, Any], with_track: bool = True) -> str:
    items = []
    if with_track and p.get("track") == "ml":
        items.append("`AI/ML`")
    items += [f"`{m}`" for m in (p.get("dl_methods") or [])[:3]]
    if p.get("is_preprint"):
        items.append("`preprint`")
    return " ".join(items)


def title_link(p: dict[str, Any]) -> str:
    title = md_escape(p.get("title", ""))
    return f"[{title}]({p['url']})" if p.get("url") else title


_MD_BREAK = "  \n  "


def zh_title(p: dict[str, Any], sep: str = "<br>") -> str:
    """Chinese title line when an academic translation is available."""
    return f"{sep}{md_escape(p['title_zh'])}" if p.get("title_zh") else ""


def category_link(cat: str, prefix: str = "docs/papers/") -> str:
    return f"[{md_escape(cat)}]({prefix}{slugify(cat)}.md)"


# ---------------------------------------------------------------------------
# README
# ---------------------------------------------------------------------------

def generate_readme(papers: list[dict[str, Any]], new_papers: list[dict[str, Any]] | None = None) -> str:
    new_papers = new_papers or []
    stats = get_statistics(papers)
    grouped = group_by_category(papers)
    date = datetime.now().strftime("%Y-%m-%d")

    parts = [
        GENERATED_MARKER,
        "# 3D Genome × Deep Learning Literature Hub",
        "> An automatically updated, relevance-filtered index of research on **3D genome organization** "
        "(Hi-C, Micro-C, TADs, loops, compartments, single-cell and imaging methods), with a focus on "
        "**deep learning and machine learning** methods.",
        " ".join([
            badge("Last updated", date, "blue"),
            badge("Papers", stats["total_papers"], "green"),
            badge("AI/ML papers", stats["ml_papers"], "purple"),
            badge("Auto update", "weekly", "brightgreen"),
        ]),
    ]
    if papers:
        parts.append(" · ".join(f"**[{name}](#{github_anchor(name)})**" for name in
                                ("Latest papers", "Browse by topic", "Most-cited AI/ML papers", "Statistics", "Usage")))

    if not papers:
        parts.append(
            "## Latest papers\n\n_The database is empty. Run `python run.py` (web GUI) or "
            "`PYTHONPATH=src python -m genome_literature run-pipeline` to build it; the weekly GitHub "
            "Actions workflow populates it automatically._"
        )
    else:
        parts.append(_latest_section(papers, new_papers))
        parts.append(_topics_section(grouped, papers))
        parts.append(_cited_section(papers))
        curated = _curated_section(papers)
        if curated:
            parts.append(curated)
        parts.append(_statistics_section(stats, papers))
    parts.append(_usage_section())
    parts.append(f"---\n\n*Last updated {date} · generated by [3DGenomeHub]({config.REPO_URL})*")
    return "\n\n".join(parts) + "\n"


def _paper_row(p: dict[str, Any]) -> str:
    cats = ", ".join(md_escape(c) for c in (p.get("categories") or [])[:2])
    meta = md_escape(short_authors(p.get("authors") or []))
    t = tags(p, with_track=False)
    return (
        f"| {p.get('date') or p.get('year') or ''} | **{title_link(p)}**{zh_title(p)}<br><sub>{meta}"
        f"{' · ' + t if t else ''}</sub> | {md_escape(p.get('journal') or '')} | {cats} |"
    )


def _latest_section(papers: list[dict[str, Any]], new_papers: list[dict[str, Any]]) -> str:
    newest = sorted(papers, key=lambda p: (p.get("date") or "", p.get("relevance", 0)), reverse=True)
    ml = [p for p in newest if p.get("track") == "ml"][:LATEST_ML_ROWS]
    other = [p for p in newest if p.get("track") != "ml"][:LATEST_OTHER_ROWS]
    new_ml = sum(1 for p in new_papers if p.get("track") == "ml")
    head = "| Date | Paper | Venue | Topics |\n|---|---|---|---|"
    lines = [
        "## Latest papers",
        "",
        f"_Last update added **{len(new_papers)}** papers ({new_ml} AI/ML)._ "
        f"Full lists: [all AI/ML × 3D genome papers](docs/papers/{ML_PAGE_SLUG}.md) · "
        "[by topic](#browse-by-topic).",
        "",
        "### AI / ML methods",
        "",
        head,
        *[_paper_row(p) for p in ml],
    ]
    if other:
        lines += ["", "### Other 3D genome methods & biology", "", head, *[_paper_row(p) for p in other]]
    return "\n".join(lines)


def _topics_section(grouped: dict[str, list[dict[str, Any]]], papers: list[dict[str, Any]]) -> str:
    year_now = datetime.now().year
    lines = [
        "## Browse by topic",
        "",
        "| Topic | Papers | AI/ML | Since last year | Latest |",
        "|---|---:|---:|---:|---|",
    ]
    ml_all = [p for p in papers if p.get("track") == "ml"]
    lines.append(
        f"| **[All AI/ML × 3D genome papers](docs/papers/{ML_PAGE_SLUG}.md)** | {len(ml_all)} | {len(ml_all)} | "
        f"{sum(1 for p in ml_all if (p.get('year') or 0) >= year_now - 1)} | "
        f"{max((p.get('date') or '' for p in ml_all), default='')} |"
    )
    for cat, items in grouped.items():
        desc = config.CATEGORIES.get(cat, {}).get("description", "")
        lines.append(
            f"| {category_link(cat)}<br><sub>{md_escape(desc)}</sub> | {len(items)} | "
            f"{sum(1 for p in items if p.get('track') == 'ml')} | "
            f"{sum(1 for p in items if (p.get('year') or 0) >= year_now - 1)} | {items[0].get('date') or ''} |"
        )
    return "\n".join(lines)


def _cited_section(papers: list[dict[str, Any]]) -> str:
    cited = sorted(
        (p for p in papers if p.get("track") == "ml" and p.get("citations")),
        key=lambda p: p.get("citations", 0), reverse=True,
    )[:TOP_CITED_ROWS]
    lines = ["## Most-cited AI/ML papers", ""]
    if not cited:
        lines.append("_Citation counts are not available yet (they come from Europe PMC, Semantic Scholar and CrossRef)._")
        return "\n".join(lines)
    lines += ["| Citations | Paper | Venue | Year |", "|---:|---|---|---|"]
    for p in cited:
        meta = md_escape(short_authors(p.get("authors") or []))
        lines.append(
            f"| {p['citations']} | **{title_link(p)}**{zh_title(p)}<br><sub>{meta} · {tags(p, with_track=False)}</sub> | "
            f"{md_escape(p.get('journal') or '')} | {p.get('year') or ''} |"
        )
    return "\n".join(lines)


def _curated_section(papers: list[dict[str, Any]]) -> str:
    curated = sorted((p for p in papers if p.get("curated")), key=lambda p: (p.get("year") or 0, p.get("title", "")))
    if not curated:
        return ""
    lines = [
        "## Landmark papers",
        "",
        "Hand-picked foundational papers (edit `papers/curated_dois.txt` to change this list).",
        "",
    ]
    for p in curated:
        lines.append(
            f"- **{title_link(p)}** — {md_escape(short_authors(p.get('authors') or []))}. "
            f"*{md_escape(p.get('journal') or '')}* ({p.get('year') or ''}) {tags(p)}"
        )
    return "\n".join(lines)


def _statistics_section(stats: dict[str, Any], papers: list[dict[str, Any]]) -> str:
    ml_by_year: dict[int, int] = {}
    for p in papers:
        if p.get("track") == "ml" and p.get("year"):
            ml_by_year[p["year"]] = ml_by_year.get(p["year"], 0) + 1
    years = sorted(stats["by_year"], reverse=True)[:12]
    peak = max((stats["by_year"][y] for y in years), default=1)
    lines = [
        "## Statistics",
        "",
        f"**{stats['total_papers']}** papers · **{stats['ml_papers']}** AI/ML · "
        f"**{stats['by_track'].get('computational', 0)}** other computational · "
        f"**{stats['by_track'].get('experimental', 0)}** experimental/biology · **{stats['preprints']}** preprints",
        "",
        "<details><summary>Papers per year</summary>",
        "",
        "| Year | All | AI/ML | |",
        "|---|---:|---:|---|",
    ]
    for y in years:
        n = stats["by_year"][y]
        lines.append(f"| {y} | {n} | {ml_by_year.get(y, 0)} | {'█' * max(1, round(n / peak * 30))} |")
    lines += ["", "</details>", ""]
    if stats["by_method"]:
        lines += ["<details><summary>Deep-learning architectures</summary>", "",
                  "| Architecture | Papers |", "|---|---:|"]
        lines += [f"| {m} | {c} |" for m, c in stats["by_method"].items()]
        lines += ["", "</details>", ""]
    lines += ["<details><summary>Sources</summary>", "", "| Database | Papers |", "|---|---:|"]
    lines += [f"| {s} | {c} |" for s, c in stats["by_source"].items()]
    lines += ["", "</details>"]
    return "\n".join(lines)


def _usage_section() -> str:
    return """## Usage

**Web app** (Windows / macOS / Linux, Python 3.9+): `python run.py` — installs dependencies on first run and
opens <http://localhost:8686> with search, filters, landscape analysis and one-click updates.
On Windows, `build_exe.bat` builds a standalone `dist/3DGenomeHub.exe`.

**Command line**

```bash
pip install -r requirements.txt
export PYTHONPATH=src
python -m genome_literature run-pipeline          # incremental update: fetch, filter, README, email
python -m genome_literature run-pipeline --backfill   # rebuild coverage from all years
python -m genome_literature search "Hi-C transformer"
python -m genome_literature stats
python -m genome_literature export --format bib   # json / csv / bib
python -m genome_literature rebuild               # re-score and re-categorize after editing config.py
python -m genome_literature serve                 # web GUI
python -m genome_literature translate --ml -n 50  # academic Chinese translation (see below)
python -m genome_literature translate-text "Title" "Abstract"
```

**How papers are selected.** Topic queries (`SEARCH_TOPICS` in `config.py`) run against PubMed, Europe PMC
(journals + bioRxiv/medRxiv preprints), a full scan of recent bioRxiv postings, arXiv, Semantic Scholar and
CrossRef. Every candidate is scored: it must contain a core 3D-genome term (Hi-C, TAD, chromatin loop, …) and
pass a weighted threshold, with penalties for look-alikes (Hi-C genome-assembly scaffolding, protein contact
maps, transactivation domains). Records are merged across databases by DOI, PMID, arXiv ID and normalized
title, then tagged with an AI/ML track, architecture families (CNN, Transformer, GNN, …) and up to three topics.

**Chinese academic translation (中文学术翻译).** Set `TRANSLATE_API_KEY` (plus `TRANSLATE_API_BASE` and
`TRANSLATE_MODEL` for providers other than DeepSeek; any OpenAI-compatible API works) in `.env`. Titles and
abstracts are translated with a curated 3D-genome / deep-learning glossary at temperature 0; every result is
checked automatically (acronyms, gene and tool names, numbers, glossary terms, completeness) and corrected once
if needed. Translations that still fail a check are marked 译文待校对 for manual proofreading. Results are cached
in `papers/translations.json`; set `"reviewed": true` on a corrected entry to lock it. In the web app use
**中英对照**, **翻译本页** or the **中文翻译** button on a paper; `run-pipeline` translates new papers automatically.

**Automation.** `.github/workflows/update.yml` runs every Monday, commits `papers/`, this README and
`docs/papers/`, and emails a digest when SMTP secrets are set. Optional secrets: `NCBI_API_KEY`,
`NCBI_EMAIL`, `SEMANTIC_SCHOLAR_API_KEY`, `SMTP_*`, `EMAIL_FROM`, `EMAIL_RECIPIENTS`, `TRANSLATE_API_KEY`,
`TRANSLATE_API_BASE`, `TRANSLATE_MODEL` (see `.env.example`).

Architecture notes: [docs/architecture.md](docs/architecture.md) · Landmark papers: `papers/curated_dois.txt`"""


# ---------------------------------------------------------------------------
# Per-topic pages
# ---------------------------------------------------------------------------

def _entry(p: dict[str, Any]) -> str:
    authors = md_escape(short_authors(p.get("authors") or [], limit=3))
    venue = md_escape(p.get("journal") or "")
    cites = f" · {p['citations']} citations" if p.get("citations") else ""
    t = tags(p)
    links = paper_links(p)
    zh = zh_title(p, _MD_BREAK)
    return (
        f"- **{title_link(p)}**{zh}  \n  {authors}. *{venue}* ({p.get('date') or p.get('year') or 'n.d.'}){cites}"
        f"{'  ' + t if t else ''}{'  · ' + links if links else ''}"
    )


def paper_list_page(title: str, description: str, papers: list[dict[str, Any]]) -> str:
    date = datetime.now().strftime("%Y-%m-%d")
    ml = sum(1 for p in papers if p.get("track") == "ml")
    lines = [
        GENERATED_MARKER,
        f"# {md_escape(title)}",
        "",
        f"> {md_escape(description)}" if description else "",
        "",
        f"[← Back to overview](../../README.md) · **{len(papers)}** papers · **{ml}** AI/ML · updated {date}",
    ]
    by_year: dict[Any, list[dict[str, Any]]] = {}
    for p in sorted(papers, key=lambda x: (x.get("date") or "", x.get("relevance", 0)), reverse=True):
        by_year.setdefault(p.get("year") or "Undated", []).append(p)
    lines.append("")
    lines.append(" · ".join(f"[{y}](#{github_anchor(str(y))})" for y in by_year))
    for y, items in by_year.items():
        lines += ["", f"## {y}", ""]
        lines += [_entry(p) for p in items]
    return "\n".join(line for line in lines if line is not None) + "\n"


def write_outputs(papers: list[dict[str, Any]], new_papers: list[dict[str, Any]] | None = None) -> list[Path]:
    """Write README.md and docs/papers/*.md; remove stale generated pages."""
    written: list[Path] = []
    cache = translator.load_cache()
    papers = translator.attach_translations(papers, cache)
    new_papers = translator.attach_translations(new_papers or [], cache)
    config.README_PATH.write_text(generate_readme(papers, new_papers), encoding="utf-8")
    written.append(config.README_PATH)

    out_dir = config.CATEGORY_PAGES_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    keep: set[Path] = set()
    if papers:
        ml = [p for p in papers if p.get("track") == "ml"]
        path = out_dir / f"{ML_PAGE_SLUG}.md"
        path.write_text(paper_list_page(
            "AI / ML × 3D Genome",
            "All papers applying deep learning or machine learning to 3D genome data.", ml), encoding="utf-8")
        keep.add(path)
        for cat, items in group_by_category(papers).items():
            path = out_dir / f"{slugify(cat)}.md"
            desc = config.CATEGORIES.get(cat, {}).get("description", "")
            path.write_text(paper_list_page(cat, desc, items), encoding="utf-8")
            keep.add(path)
    for path in out_dir.glob("*.md"):
        if path not in keep and path.read_text(encoding="utf-8").startswith(GENERATED_MARKER):
            path.unlink()
    written.extend(sorted(keep))
    logger.info("Wrote README.md and %d topic pages", len(keep))
    return written
